# Generated by Django 3.1.1 on 2020-10-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('tools', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('img_name', models.CharField(max_length=100)),
            ],
        ),
    ]
